<?php
// Fichier de langue francais du mod stats
define ( 'mods_stats_guests' , 'Visiteurs' );
define ( 'mods_stats_unknow' , 'Inconnu' );
define ( 'mods_stats_ie',"IE");
define ( 'mods_stats_mozilla',"Mozilla");
define ( 'mods_stats_ubuntu',"Ubuntu");
define ( 'mods_stats_debian',"Debian");
define ( 'mods_stats_ff',"Firefox");
define ( 'mods_stats_ns',"Netscape");
define ( 'PAGES_VUES' , 'Pages vues' );
define ( 'mods_stats_ib',"Icebrowser");
define ( 'mods_stats_konqueror',"Konqueror");
define ( 'SEE_RECORDS' , 'Voir les records' );
define ( 'mods_stats_opera',"Opera");
define ( 'REGISTERED_USERS' , 'Utilisateurs' );
define ( 'mods_stats_webtv',"WebTV");
define ( 'CONNECTED_GUESTS' , 'Invités en ligne' );
define ( 'CONNECTED_MEMBERS' , 'Membres en ligne' );
define ( 'VISITES_TODAY' , 'Visites aujourd\'hui' );
define ( 'mods_stats_safari',"Safari");
define ( 'mods_stats_kanari',"Kanari");
define ( 'mods_stats_bots',"Bot");
define ( 'mods_stats_bot_google' , 'GoogleBot' );
define ( 'mods_stats_yahoo',"Yahoo");
define ( 'mods_stats_altavista',"Altavista");
define ( 'mods_stats_msn',"Msn");
define ( 'mods_stats_none_stats' , 'Aucune Stats' );
define ( 'mods_stats_navigators_stats' , 'Statistiques des navigateurs' );
define ( 'mods_stats_period_stat' , 'Statistiques périodique' );
define ( 'mods_stats_pays_stat' , 'Statistiques par pays' );
define ( 'mods_stats_theme_stat' , 'Statistiques par theme' );
define ( 'mods_stats_more_stats' , 'Plus de stats' );
define ( 'PAGES_DETAILS' , 'Details des Pages Vues' );
define ( 'mods_stats_index' , 'Statistiques' );
define ( 'mods_stats_os_stats' , 'Statistiques des O.S.' );
define ( 'mods_stats_windob' , 'Windows' );
define ( 'NB_TOTAL_PAGES' , 'Nombre Total de Pages Vues' );
define ( 'mods_stats_windob_me' , 'Windows Me' );
define ( 'mods_stats_windob_98' , 'Windows 98' );
define ( 'mods_stats_windob_2000' , 'Windows 2000' );
define ( 'DAY' , 'Jour' );
define ( 'mods_stats_windob_95' , 'Windows 95' );
define ( 'mods_stats_windob_nt' , 'Windows NT' );
define ( 'SEE_STATS_IN' , 'Voir les Stats en' );
define ( 'SEE_DURING_MONTH' , 'Voir le mois de' );
define ( 'STATS_DURING_ALL_PERIOD' , 'Statistiques depuis la création du site' );
define ( 'SEE_STATS_IN_ALL_PERIOD' , 'Voir les statistiques sur toute la période' );
define ( 'mods_stats_windob_xp' , 'Windows Xp' );
define ( 'STATS_DURING_LAST_SEVEN' , 'Statistiques sur les 7 derniers jours' );
define ( 'mods_stats_linux' , 'Linux' );
define ( 'mods_stats_sunos' , 'SunOs' );
define ( 'mods_stats_freebsd' , 'FreeBSD' );
define ( 'mods_stats_openbsd' , 'OpenBSD' );
define ( 'mods_stats_vista' , 'Windows Vista' );
define ( 'mods_stats_unix' , 'Unix' );
define ( 'mods_stats_mac' , 'Mac' );
define ( 'mods_stats_bot' , 'Bot' );
define ( 'mods_stats_beos' , 'Be Os' );

define ( 'STATS_SUCCESSFULLY_INSTALLED' , 'Statistiques installés avec succès' );
?>