<?php

// Fichier de langue francais de l'espace membre
define ( 'SPACEMEMBER' , 'Espace Membre' );
define ( 'spacemember_functionment' , 'Fonctionnement de l\'espace membre' );
define ( 'operatory_mode' , 'Mode opératoire' );
define ( 'already_connected' , 'Vous êtes déja connecté' );
define ( 'profil_modif' , 'Modifier son profil' );
define ( 'register_pseudo_invalid' , 'Pseudo invalide' );
define ( 'profil_modif_def' , 'Cliquez sur l\'onglet "Modifier mon profil" se trouvant a l\'accueil de votre espace membre' );
define ( 'little_rappel' , 'Petit rappel' );
define ( 'mdp_more_5_char' , 'Pour valider votre mot de passe celui-ci doit contenir au minimum 5 caractéres.' );
define ( 'create_a_note_def' , 'Créer une note</strong> : Cliquez sur l\'onglet <i>"Mon	bloc note"</i>  se trouvant a l\'accueil de votre espace membre' );
define ( 'how_to_create_note' , 'Pour créer une note cliquez sur <i>"Ecrire une note"</i>' );
define ( 'how_to_see_or_delete_note' , 'Pour voir et supprimez vos notes cliquez sur <i>"Vos notes"</i>' );
define ( 'send_mp' , 'Envoyer un message privé' );
define ( 'how_to_send_mp' , 'Pour envoyer un MP cliquez sur l\'onglet <i>"Envoyer un MP "</i>  se trouvant a l\'accueil de votre espace membre' );
define ( 'how_to_see_mp' , 'Pour voir vos MP cliquez sur l\'onglet <i>"Voir mes MP "</i>  se trouvant a l\'accueil de votre espace membre' );
define ( 'to_know_if_mp' , 'Pour savoir si vous avez de nouveaux messages rendez vous a l\'index de votre espace membre' );
define ( 'back_to_spacemember' , 'Retour à l\'espace membre' );
define ( 'identifiant' , 'Identifiant' );
define ( 'password' , 'Mot de passe' );
define ( 'email_cant_be_send' , 'L\'E-Mail n\'a pas pu être envoyé' );
define ( 'PWD_RESENDED' , 'Votre mot de passe à ete renvoye à votre adresse email' );
define ( 'to_remember' , 'Se souvenir de moi' );
define ( 'not_register' , 'Pas encore inscrit ?' );
define ( 'forgetted_password' , 'Mot de Passe oublié ?' );
define ( 'see_own_mp' , 'Voir ses messages privés' );
define ( 'new_mp' , 'nouveau(x) MP' );
define ( 'YOU_MUST_BE_CONNECTED' , 'Vous devez être connecté pour accèder au site...' );
define ( 'IF_NOT_CLICK' , 'Si vous n\'etes pas inscrit, cliquez' );
define ( 'TO_REGISTER' , 'pour vous inscrire.' );
define ( 'messagerie' , 'Messagerie' );
define ( 'identification' , 'Identification' );
define ( 'please_enter_login' , 'Entrez votre login' );
define ( 'CONNECTION_INDISPENSABLE' , 'Connection indispensable' );
define ( 'please_enter_password' , 'Entrez votre mot de passe' );

define ( 'REDIRECTION' , 'Redirection en cours ... Veuillez attendre ou cliquez ici pour être redirigé directement.' );

define ( 'modif_profil' , 'Modifier mon profil' );
define ( 'change_language' , 'Changer la langue' );
define ( 'NONE_PREVIEW' , 'Pas de prévisualisation disponible' );
define ( 'change_theme' , 'Modifier le thème' );
define ( 'my_infos' , 'Mes infos' );
define ( 'spacemember_help' , 'Comprendre l\'espace membre' );
define ( 'personnal_infos' , 'Informations personelles' );
define ( 'user_info' , 'Information sur l\'utilisateur' );
define ( 'your_fiche' , 'Votre FICHE' );
define ( 'pseudo' , 'Pseudo' );
define ( 'first_name' , 'Prénom' );
define ( 'NONE_COMMENT' , 'Aucun Commentaire' );
define ( 'NONE_POST' , 'Aucune Réponse' );
define ( 'NONE_TOPIC' , 'Aucun Sujet' );
define ( 'LOCKED_THEME' , 'L\'administrateur vous oblige à utiliser le thème par défaut !' );
define ( 'email' , 'Email' );
define ( 'my_mail_adress' , 'Mon adresse E-Mail' );
define ( 'inscription_date' , 'Date d\'inscription' );
define ( 'my_complete_fiche' , 'Ma fiche d\'identité complète' );
define ( 'purpose_a_news' , 'Proposer une news' );
define ( 'your_messagerie' , 'Votre MESSAGERIE' );
define ( 'archived_mp' , 'message(s) archivé(s)' );
define ( 'see_my_mp' , 'Voir mes MP' );
define ( 'send_a_mp' , 'Envoyez un MP' );
define ( 'please_choose_language' , 'Veuillez selectionner une langue' );
define ( 'confirmation' , 'Confirmation' );
define ( 'message_sended' , 'Message envoyé' );
define ( 'youll_be_redirect' , 'Vous allez être redirigé!' );
define ( 'Destinataire' , 'Destinaire' );
define ( 'Author' , 'Auteur' );
define ( 'Topic' , 'Sujet' );
define ( 'AVATAR' , 'Avatar' );
define ( 'UNACTIVATED' , 'Non-Activé' );
define ( 'BANNED' , 'Banni' );
define ( 'NONEE' , 'Aucune' );
define ( 'ACTIVITY' , 'Activité' );
define ( 'NB_AVERTISSEMENTS' , 'Nombre d\'avertissements' );
define ( 'LAST_ACTIVITY' , 'Dernière Activité' );
define ( 'LAST_POST' , 'Dernier Post' );
define ( 'NB_POSTS' , 'Nombre de Posts' );
define ( 'REPUTATION_PTS' , 'Points de reputation' );
define ( 'NEVER' , 'Jamais' );
define ( 'FORUM_PARTICIPATION' , 'Participation dans le forum' );
define ( 'Content' , 'Contenu' );
define ( 'your_content' , 'Votre contenu' );
define ( 'please_choose_theme' , 'Veuillez selectionner un théme' );
define ( 'Theme' , 'Thème' );
define ( 'your_theme' , 'Votre Thème' );
define ( 'found_his_password' , 'Retrouver son mdp...' );
define ( 'verif_error_retry' , 'Erreur de vérification, votre mot de passe ne sera pas renvoyez, veuillez reessayer' );
define ( 'your_new_password' , 'Votre nouveau mot de passe' );
define ( 'update_pass_request' , 'Demande de changement de mot de passe' );
define ( 'email_sended_1' , 'Un E-Mail à ete envoye a ladresse que vous avez mentionnez, cliquez sur le lien place dans l\'email pour avoir un nouveau mot de passe' );
define ( 'none_users_with_it' , 'Il n\'existe aucun utilisateur avec cette adresse' );
define ( 'please_enter_your_mail_addr' , 'Veuillez entrer votre adresse E-Mail afin que l\'on vous renvoie votre mot de passe' );
define ( 'already_CONNECTED' , 'Vous etes deja connecte, logiquement si vs zetes connectes c ke vs avez po perdu votre mdp !!!' );
define ( 'warning' , 'Attention' );
define ( 'please_enter_password_more_4' , 'Veuillez entrez un mot de passe de plus de 4 caractères' );
define ( 'successfully_updated' , 'Modifi&eacute; avec succ&egrave;s' );
define ( 'profil_updated_successfully' , 'Votre profil &agrave; &eacute;t&eacute; modifi&eacute; avec succ&egrave;s' );
define ( 'update_profil' , 'Modification du profil' );
define ( 'please_complete_password' , 'Merci de bien vouloir compléter le champ Password' );
define ( 'same_password' , 'Le mot de passe est identique' );
define ( 'wrong_password' , 'Les mots de passes sont différents' );
define ( 'valid_email' , 'Adresse E-Mail valide' );
define ( 'not_valid_email' , 'Adresse E-Mail non valide' );
define ( 'obligatory_fields' , 'Champs obligatoires' );
define ( 'confirm_password' , 'Confirmez votre mot de pass' );
define ( 'localization' , 'Localisation' );
define ( 'sex' , 'Sexe' );
define ( 'man' , 'Homme' );
define ( 'woman' , 'Femme' );
define ( 'date_of_birth' , 'Date de naissance' );
define ( 'my_mess' , 'Mes messageries' );
define ( 'adress_icq' , 'Adresse Icq' );
define ( 'adress_msn' , 'Adresse Msn' );
define ( 'adress_aim' , 'Adresse Aim' );
define ( 'adress_yahoom' , 'Adresse Yahoo Messenger' );
define ( 'other' , 'Autres' );
define ( 'web_site' , 'Site Web' );
define ( 'signature' , 'Signature' );
define ( 'del_mess' , 'Suppression de messages' );
define ( 'selection_mess_delet' , 'Les messages sélectionnés ont été supprimés. Vous allez maintenant être redirigé!' );
define ( 'mp' , 'MP' );
define ( 'none_mp' , 'Aucun Message privé' );
define ( 'seen_your_messages' , 'Apercu de vos messages privés' );
define ( 'shipper' , 'Expéditeur' );
define ( 'STATUT' , 'Statut' );
define ( 'delet' , 'Supprimer' );
define ( 'HAS_BEEN_DELETED' , 'a été supprimé' );
define ( 'THE_MESS' , 'Le message' );
define ( 'new_mess' , 'Nouveau message' );
define ( 'answer_sent' , 'réponse envoyée' );
define ( 'answer_mp' , 'Répondre à un message privé' );
define ( 'recipient' , 'Destinataire' );
define ( 'dont_modif' , 'Ne pas modifier' );
define ( 'preceding_message' , 'Message précédent' );
define ( 'answer' , 'Repondre' );
define ( 'envoy_by' , 'Envoyé par' );
define ( 'to_print_this_mess' , 'Imprimer ce message' ); 
define ( 'you_have' , 'Vous avez' );
define ( 'modif_success' , 'Les modifications ont été effectué avec succés' );
define ( 'parameters' , 'Paramètres' );
define ( 'time_sone' , 'Fuseau horaire' );
define ( 'pb_hours' , 'Si vous avez un affichage avec 1h de retard, cochez cette option(gestion heure été/heure d\'hiver)' );
define ( 'current_hour' , 'Heure actuelle' );
define ( 'menu' , 'Menu' );
define ( 'PARAMS' , 'Autres Paramètres' );
define ( 'my_notes' , 'Mes notes' );
define ( 'write_note' , 'Ecrire une note' );
define ( 'writing_note' , 'Ecriture d\'une note' );
define ( 'form' , 'Formulaire' );
define ( 'title_note' , 'Titre de la note' );
define ( 'content_note' , 'Contenu de la note' );
define ( 'note_save' , 'Votre note a &eacute;t&eacute; enregistr&eacute;' );
define ( 'no_note' , 'Aucune note' );
define ( 'click' , 'Cliquez' );
define ( 'here' , 'ici' );
define ( 'HIDE_PERSONNAL_INFOS' , 'Afficher ou Cacher les Informations personnelles aux autres membres' );
define ( 'EMAIL_ADRESS' , 'Adresse E-Mail' );
define ( 'MSN_ADRESS' , 'Adresse Msn' );
define ( 'ICQ_ADRESS' , 'Adresse Icq' );
define ( 'YAHOOM_ADRESS' , 'Adresse Yahoo Messenger' );
define ( 'AIM_ADRESS' , 'Adresse Aim' );
define ( 'BIRTHDAY_DATE' , 'Date d\'anniversaire' );
define ( 'LOCALISATION' , 'Localisation' );
define ( 'APPEAR_OFFLINE' , 'Apparaitre Hors Ligne sur le site' );
define ( 'to_post_note' , 'pour poster une note' );
define ( 'to_back_note' , 'pour retourner à la visualisation des notes' );
define ( 'note' , 'Note' );
define ( 'profile_of' , 'Profil de' );
define ( 'perso_info' , 'Informations personnelles' );
define ( 'member' , 'Membre' );
define ( 'member_vip' , 'Membre VIP' );
define ( 'NOTE_DELETED' , 'Note supprimé' );
define ( 'yahoom' , 'Yahoo Messenger' );
define ( 'modo' , 'Modérateur' );
define ( 'admin' , 'Administrateur' );
define ( 'date_of_inscription' , 'Date d\'inscription' );
define ( 'not_indicated' , 'Non indiqué' );
define ( 'contact' , 'Contact' );
define ( 'PPRINT' , 'Afficher' );
define ( 'HIDE' , 'Cacher' );
define ( 'help_member' , 'Aide pour l\'espace membre' );
define ( 'CONNECTED' , 'Vous êtes désormais connecté' );
define ( 'ERROR_LOGIN' , 'Erreur lors de la connection' );
define ( 'profil_updated_sucessfully' , 'Profil mis à jour avec succès' );
define ( 'mods_espace_membre_disconnect ' , 'Déconnection' );
define ( 'see_ur_profil' , 'Voir votre profil' );
define ( 'u_can_send_multy' , 'Pour envoyer un message a plusieurs personnes, separarez les par des ; ' );
define ( 'memberlist' , 'Liste des membres' );
define ( 'no_titre' , 'Pas de titre' );
define ( 'lang' , 'Langue' );
define ( 'connection' , 'Connection' );
define ( 'modif_param' , 'Modification' );

define ( 'ne_pas_modifier' , 'Ne pas modifier' );
define ( 'choose_local_avatar' , 'Choisir un des avatar du site' );
define ( 'choose_externe_avatar' , 'Choisir un avatar externe' );
define ( 'upload_from_computer' , 'Envoyer depuis votre ordinateur' );
define ( 'choose' , 'Choisissez' );
define ( 'avatar' , 'Avatar' );
define ( 'your_actual_avatar' , 'Votre avatar actuel' );
define ( 'your_new_avatar' , 'Votre nouvel avatar' );

define ( 'ACCOUNT_UNACTIVATED' , 'Votre compte n\'as pas été activé ou vous avez été bannis !' );

?>