<?php

// Fichier de langue francais de l'administration

define ( 'TABLE' , 'Table' );
define ( 'STRUCTURE' , 'Structure' );
define ( 'PRINT_TB' , 'Afficher' );
define ( 'EMPTY_TB' , 'Vider' );
define ( 'MEMBERLIST' , 'Liste des membres' );
define ( 'CANT_BE_DELETED_OR_EDITED' , 'Ce membre ne peut être modifié ou supprimé' );
define ( 'HOWTO_DEGODEISE' , 'Comment le modifier ou le supprimer' );
define ( 'HOWTO_DEGODEISE_TXT' , '
Si vous désirez tout de même supprimer ce membre, rendez le éditable en téléchargant le fichier <b>"./includes/config.php"</b> de votre site, <br />Ouvrez ce fichier et retirez son id de la liste "$god_user" puis remettez ce fichier sur votre Site.
<br /><br />
Par exemple si son id est le 61, on peut avoir dans le fichier config.php : <i>$god_user = \'1,61\';</i> remplacez alors cette ligne par : <i>$god_user = \'1\';</i>' );
define ( 'ALL' , 'Tout' );
define ( 'UPDATE_GRADE' , 'Modifier le Grade' );
define ( 'DEFAULT_FUSEAU' , 'Fuseau horaire par défaut' );
define ( 'EXPORT' , 'Exporter' );
define ( 'ADD_TABLE' , 'Ajouter une table' );
define ( 'ADD_THE_TABLE' , 'Ajouter la table' );
define ( 'TYPE' , 'Type' );
define ( 'MAIL_NEW_MDP' , 'E-Mail de regeneration de Mot de Passe 2' );
define ( 'RECUP_PASS_MAIL' , 'E-Mail de regeneration de Mot de Passe 1' );
define ( 'MAINTENANCE_NOTES' , 'Notes de maintenance' );
define ( 'ENABLE_MAINT' , 'Activer la maintenance' );
define ( 'USE_DEFAULT_THEME' , 'Forcer les utilisateurs a utiliser le thème par défaut' );
define ( 'DEFAULT_LANGUAGE' , 'Langue par défaut' );
define ( 'DEFAULT_THEME' , 'Thème par défaut' );
define ( 'ENABLED' , 'Activé' );
define ( 'DISABLED' , 'Désactivé' );
define ( 'ADMIN_VALID' , 'Validation par l\'admin' );
define ( 'EMAIL_VALID' , 'Validation par E-Mail' );
define ( 'ONLY_ACTIVATE_IF_PICTURE' , 'N\'activez le code de sécurité que si l\'image s\'affiche correctement ci-dessous' );
define ( 'BB_FORM' , 'Formulaire Simple' );
define ( 'WISY_FORM' , 'Formulaire Wysiwyg' );
define ( 'USER_VALIDATION' , 'Validation des utilisateurs' );
define ( 'CLOSE_REGISTRATION' , 'Interdire l\'inscription à votre site' );
define ( 'FORCE_LOGIN' , 'Obliger les utilisateurs &agrave; se connecter pour acceder au site' );
define ( 'FORMTYPE' , 'Type de Formulaire' );
define ( 'SECU_CODE' , 'Code de sécurité lors de l\'inscription' );
define ( 'MOD_UNINSTALLED' , 'Module désinstallé avec succ&egrave;s' );
define ( 'MODULE_NOT_INSTALLABLE' , 'Erreur, ce module n\'est pas installable !' );
define ( 'SURE_TO_DEL' , 'Etes vous sur de vouloir désinstaller le module' );
define ( 'DEFAULT_NAME' , 'Defaut' );
define ( 'ORR' , 'ou' );
define ( 'THIS_WILL_DESTROY_DATA' , 'Cela detruira tout le contenu de ce module !' );
define ( 'INSTALL_MOD' , 'Installer un module' );
define ( 'UNINSTALL_MOD' , 'Désinstaller un module' );
define ( 'NONE_MOD_TO_INSTALL' , 'Aucun module &agrave; installer n\'a été trouvé !' );
define ( 'NONE_MOD_TO_UNINSTALL' , 'Aucun module &agrave; désinstaller n\'a été trouvé !' );
define ( 'PLACED_AFTER' , 'Placé après' );
define ( 'ADD_FIELD' , 'Ajouter un champ' );
define ( 'EXTRA' , 'Extra' );
define ( 'ARE_YOU_SURE_TO_DEL' , 'Etes vous sur de vouloir supprimer la table' );
define ( 'ARE_YOU_SURE_TO_EMPTIE' , 'Etes vous sur de vouloir vider la table' );
define ( 'WARNING' , 'Attention cela peut nuir au bon fonctionnement de votre site' );
define ( 'NO_WARNING' , 'Cette Table n\'est pas une table indispensable pour CrazyCms' );
define ( 'TABLE_SUCCESSFULLY_CREATED' , 'Table crée avec succ&egrave;s' );
define ( 'TABLE_SUCCESSFULLY_EMPTIED' , 'Table vidé avec succ&egrave;s' );
define ( 'TABLE_SUCCESSFULLY_DELETED' , 'Table supprimé avec succ&egrave;s' );
define ( 'TABLE_NAME' , 'Nom de la table' );
define ( 'FIELD_NBR' , 'Nombre de champs' );
define ( 'DO_QUERY' , 'Executer une requête SQL' );
define ( 'REGISTER_MAIL' , 'Adresse E-Mail' );
define ( 'QUERY_DONE' , 'Requête executé !' );
define ( 'MIN_RANK' , 'Rang' );
define ( 'MODULE' , 'Module' );
define ( 'LINE_SUCCESSFULLY_UPDATED' , 'La ligne &agrave; été modifié' );
define ( 'LINE_SUCCESSFULLY_INSERTED' , 'La ligne &agrave; été inséré' );
define ( 'ADD_BLOC' , 'Ajouter un bloc' );
define ( 'INSERT_NEW_LINE' , 'Inserer une nouvelle ligne' );
define ( 'CHOOSE_TABLE' , 'Choisissez les tables &agrave; exporter' );
define ( 'ACTUAL_MOD' , 'Module Actuel' );
define ( 'LISTEMOD' , 'Liste des modules' );
define ( 'LISTEBLOC' , 'Liste des blocs' );
define ( 'UP_BLOC' , 'Monter le Bloc' );
define ( 'DOWN_BLOC' , 'Descendre le Bloc' );
define ( 'MANAGE_BDD' , 'Gérer la Base de Donnée');
define ( 'EXPORT_BDD' , 'Exporter la base de donnée' );
define ( 'BLOCS_MANUAL' , 'Blocs crées' );
define ( 'FREEPAGES_CREATED' , 'Pages Libres' );
define ( 'TEXT_PAGES_CREATED' , 'Pages Textes crées' );
define ( 'DATE' , 'Date' );
define ( 'BAN_A_USER' , 'Banîr un utilisateur' );
define ( 'WEBSITE' , 'Site' );
define ( 'UNBAN_A_USER' , 'D&eacute;-bannîr un utilisateur' );
define ( 'UNBAN' , 'D&eacute;-Bannir' );
define ( 'DELETING_AN_USER' , 'Suppression d\'un utilisateur' );
define ( 'USERS_UNBAN_SUCCESSFULLY' , 'Utilisateur d&eacute;-banni avec succ&egrave;s' );
define ( 'NOT_BAN_USER' , 'Cet utilisateur n\'est pas banni' );
define ( 'BAN' , 'Bannir' );
define ( 'HERITED_PERMISSION' , 'Lorsqu\'un membre appartient à un grade, il possède les permissions de son grade en plus de celle que vous pouvez lui rajouter ci dessous' );
define ( 'TO_SEE_GO_TO' , 'Pour voir les permissions attribués à chacun des grades, rendez vous dans' );
define ( 'GRADES_ADMINIS' , 'l\'administration des grades.' );
define ( 'HAS_ADDED_MODULE' , 'A ajouté un module' );
define ( 'HAS_DELETED_MODULE' , 'A supprimé un module' );
define ( 'HAS_DELETED_BLOC' , 'A supprimé un bloc' );
define ( 'HAS_ADDED_BLOC' , 'A ajouté un bloc' );
define ( 'HAS_UPDATED_MODDEM' , 'A modifié le module de démarrage' );
define ( 'HAS_OPTIMIZED_BDD' , 'A optimisé la base de donnée' );
define ( 'HAS_DELETED_TABLE' , '<font color="red">A supprimé une table !</font>' );
define ( 'HAS_EXECUTED_QUERY' , '<font color="red">A effectué une requête manuelle !</font>' );
define ( 'HAS_TRUNCATED_TABLE' , '<font color="red">A vidé une table !</font>' );
define ( 'USERS' , 'Utilisateurs' );

define ( 'HAS_DELETED_USER' , '<font color="red">A supprimé un utilisateur</font>' );
define ( 'HAS_BANNED_USER' , '<font color="orange">A banni un utilisateur</font>' );
define ( 'HAS_UNBANNED_USER' , '<font color="orange">A dé-banni un utilisateur</font>' );
define ( 'HAS_UPDATED_USER' , '<font color="orange">A modifié un utilisateur</font>' );
define ( 'HAS_ACTIVATED_USER' , 'A activé un utilisateur' );
define ( 'HAS_EXPORTED_TABLE' , '<font color="orange">A exporté une ou plusieurs table</font>' );
define ( 'HAS_DELETED_ROW' , '<font color="orange">A supprimé la ligne d\'une table</font>' );
define ( 'HAS_UPDATED_ROW' , '<font color="orange">A modifié la ligne d\'une table</font>' );
define ( 'HAS_ADDED_ROW' , '<font color="orange">A ajouté une ligne à une table</font>' );
define ( 'HAS_ADDED_TABLE' , '<font color="orange">A ajouté une table</font>' );
define ( 'USERS_BAN_SUCCESSFULLY' , 'Utilisateur Banni avec succ&egrave;s' );
define ( 'MEMBER_LIST' , 'Liste des membres' );
define ( 'BAN_MANAGE' , 'Gestion des Bannissements' );
define ( 'USERS_NOT_VALIDATED' , 'Utilisateurs en attente d\'activation' );
define ( 'ACTIV' , 'Activer' );
define ( 'MANAGEMENT' , 'Gestion' );
define ( 'MSN' , 'Adresse MSN' );
define ( 'HAS_UPDATED_ACCESS' , 'A modifié les accès à l\'administration' );
define ( 'GEN_ADMIN' , 'Administration' );
define ( 'HAS_EMPTIED_CACH' , 'A vidé le cache' );
define ( 'HAS_EMPTIED_ALL_CACH' , 'A vidé l\'intégralité du cache' );
define ( 'HAS_UPDATED_DEFAULT_SYNTAX' , 'A modifié la syntaxe par défaut' );
define ( 'HAS_UPDATED_GRADE' , 'A modifié un grade' );
define ( 'HAS_DELETED_GRADE' , 'A supprimé un grade' );
define ( 'HAS_ADDED_GRADE' , 'A ajouté un grade' );
define ( 'HAS_UPDATED_GEN_CONFIG' , 'A modifié la configuration générale' );
define ( 'HAS_UPDATED_DEFAULT_FUSEAU' , 'A modifié le fuseau par défaut' );
define ( 'ICQ' , 'Adresse ICQ' );
define ( 'AIM' , 'Adresse AIM' );
define ( 'SITE' , 'SITE' );
define ( 'SIGN' , 'Signature' );
define ( 'ADMIN_INTERFACE' , 'Interface' );
define ( 'GRADE_UNKNOWN' , 'Inconnu' );
define ( 'ADM_OPTIONS' , 'Administration du portail' );
define ( 'MODS_ADM' , 'Administration des modules' );
define ( 'MAIN_OPTIONS' , 'Options principales' );
define ( 'NOM_SITE' , 'Nom du site' );
define ( 'DESC' , 'Descriptif' );
define ( 'MC' , 'Mots Clefs' );
define ( 'EDITO' , 'Editorial' );
define ( 'THE_PERMISSIONS' , 'Les permissions' );
define ( 'COPYRIGHTS' , 'Copyrights' );
define ( 'RESET' , 'R&eacute;tablir' );
define ( 'LOGO' , 'Url du Logo' );
define ( 'SECONDARY_OPTIONS' , 'Options secondaires' );
define ( 'ADMIN_MOD_ACC' , 'Modifier votre module d\'accueil' );
define ( 'ADMIN_DEL_BLOC' , 'Êtes vous sur de vouloir supprimer ce bloc ?' );
define ( 'GEN' , 'General' );
define ( 'NAME' , 'Nom' );
define ( 'EMPT' , 'Vider' );
define ( 'EMPTY_ALL' , 'Vider l\'intégralité du cache' );
define ( 'CACHE_EMPTIED_SUCCESSFULLY' , 'Cache vidé avec succès' );
define ( 'CACHE_CONTENT' , 'Contenu du Cache' );
define ( 'PERMS' , 'Permissions' );
define ( 'GRADES_CREATED_SUCCESSFULLY' , 'Grade crée avec succès' );
define ( 'GRADES_UPDATED_SUCCESSFULLY' , 'Grade mis à jour avec succès' );
define ( 'GRADE_SUCCESSFULLY_DELETED' , 'Grade supprimé avec succès' );
define ( 'REALLY_SURE_TO_DELETE_GRADE' , 'Etes vous vraiment sur de vouloir supprimer ce grade ?

Si certains membres ont ce grade, leur grade sera défini a "Membre".');
define ( 'DEFAULT_PERMS' , 'Permissions par d&eacute;faut' );
define ( 'MEMBER_DELETED' , 'Membre supprim&eacute;' );
define ( 'MANAGE_DEFAULT_PERM' , 'Gêrer les permissions par d&eacute;faut &agrave; l\'inscription' );
define ( 'MANAGE_GUESTS_PERM' , 'Gêrer les permissions par d&eacute;faut des invit&eacute;s' );
define ( 'GUESTS_PERM' , 'Permissions des Invit&eacute;s' );
define ( 'OPTIMIZE' , 'Optimis&eacute;' );
define ( 'THE_TABLE' , 'La table' );
define ( 'HAS_BEEN_OPTIMIZED' , '&agrave; &eacute;t&eacute; optimis&eacute; et repar&eacute;' );
define ( 'BDD_OPTIMIZED_IN' , 'La Base de Donn&eacute;e &agrave; &eacute;t&eacute; optimis&eacute; en' );
define ( 'SECONDS' , 'secondes' );
define ( 'SQL_MANAGING' , 'Gestion de la Base de Donn&eacute;e' );
define ( 'OPTIMIZE_ALL_TABLE' , 'Optimiser toutes les tables de la base' );
define ( 'VISIBLE' , 'Rendre visible' );
define ( 'INVISIBLE' , 'Rendre invisible' );
define ( 'BLOC_ADDED_SUCCESSFULLY' , 'Bloc ajout&eacute; avec succ&eacute;s' );
define ( 'BOOT_MOD_UPDATED' , 'Module d\'accueil mis &agrave; jour avec succ&eacute;s' );
define ( 'BLOC_DELETED_SUCCESSFULLY' , 'Bloc supprim&eacute; avec succ&eacute;s' );
define ( 'SQL' , 'SQL' );
define ( 'PSEUDO_WHO_BEGIN_BY_LETTER' , 'Pseudo commençant par un chiffre' );
define ( 'PSEUDO_WHO_BEGIN_NBR' , 'Pseudo commençant par la lettre ' );
define ( 'PSEUDO' , 'Pseudo' );
define ( 'ADD_GRADE' , 'Ajouter un Grade' );
define ( 'GRADES' , 'Grades' );
define ( 'GRADES_MANAGEMENT' , 'Gestion des Grades' );
define ( 'GRADE_NAME' , 'Nom du Grade' );
define ( 'EDIT' , 'Editer' );
define ( 'DELETE' , 'Supprimer' );
define ( 'ACTION' , 'Action' );
define ( 'NOMANY_MBR_TT' , 'Aucun membre trouv&eacute; avec ces crit&egrave;res' );
define ( 'USERS_PROFIL' , 'Profil de ' );
define ( 'SEE_ADMIN_MOD' , 'Gestion des acc&egrave;s &agrave; l\'administration' );
define ( 'OPTION_SITE' , 'Options de votre site' );
define ( 'MODS' , 'Modules' );
define ( 'USERS_MANAGEMENT' , 'Gestion des Utilisateurs' );
define ( 'LOGS' , 'Logs' );
define ( 'LOG_ADM' , 'Gestion des journaux d\'administration' );
define ( 'SEE_LOGS' , 'Voir les Journaux' );
define ( 'TRUNCATE_LOGS' , 'Vider les Logs' );
define ( 'LOGS_PRESENT' , 'Journaux présents' );
define ( 'GODS_ADMINS' , 'Administrateurs Dieu' );
define ( 'PRINTING_LOGS_FROM' , 'Affichage des Journaux du groupe' );
define ( 'LOG_MODULE' , 'Module' );
define ( 'LOGS_USER' , 'Utilisateur' );
define ( 'HAS_TRUNCATED_LOG' , 'A vidé un journal' );
define ( 'HAS_DEL_A_LOG' , 'A supprimé une action d\'un journal' );
define ( 'LOG' , 'Logs' );
define ( 'NONE_LOG_HERE' , 'Aucun Log présent' );
define ( 'LOG_DELETED_SUCCESSFULLY' , 'Action supprimée avec succès' );
define ( 'LOGS_TO_DEL' , 'Choisissez le journal à supprimer' );
define ( 'LOG_TRUNCATED_SUCCESSFULLY' , 'Le journal à été supprimé avec succès' );
define ( 'LOG_CANT_BE_TRUNCATED' , 'Le log n\'a pas pu être supprimé ( cela peut être du à un probleme du chmod sur le fichier ./mods/admin/log.php ;)' );
define ( 'LOG_ACTION' , 'Action effecutée' );
define ( 'LOG_DATE' , 'Date' );
define ( 'LOG_DEL' , 'Effacer cette action' );

define ( 'RANK' , 'Rang requis' );

define ( 'GESTION_ALERTE' , 'Gestion des alertes' );
define ( 'SEE_ADMIN_CACHE' , 'Administration du Cache' );
define ( 'CACHE' , 'Cache' );
define ( 'GESTION_ALERT' , 'Gestion des messages d\'alerte' );
define ( 'DEFAULT_ALERT' , 'Alerte par default' );
define ( 'ADD_ALERTE' , 'Ajouter une alerte' );
define ( 'SEND' , 'Envoyer' );
define ( 'ALERT_MAJ_OK' , 'Mise &agrave; jour des alertes effectu&eacute;es avec succ&eacute;s' );
define ( 'ALERT_ADDITION_SUCCESSFULLY' , 'Alerte ajout&eacute;e avec succ&eacute;s' );

?>